http:
  port: 8080

apiEndpoints:
  appointment:
    host: 'localhost'
    paths: 
      - '/api/v1/first'
      - '/api/v1/appointment/:id'
      - '/api/v1/appointments'
      - '/api/v1/addAppointment'

serviceEndpoints:
  appointment:
    url: 'http://localhost:5005'

policies:
  - proxy

pipelines:
  - name: default
    apiEndpoints:
      - appointment
    policies:
      - proxy:
          - action:
              serviceEndpoint: appointment
