version: '3.7'

services:
  medest-forum-ms :
      build : 
         context : .
         dockerfile : Dockerfile
      image : node:lastest
      container_name: medest-forum-ms
      restart : always 
      stdin_open: true 
      tty : true
      command : /usr/src/app/node_modules/.bin/nodemon server.js
      volumes :
        - ./:/usr/src/app
        - /usr/src/app/node_modules
      ports :
       - "5010:5000"
      depends_on:
       - mongodb-forum-ms
      env_file : ./config/.env
      networks:
       - medest-network

  mongodb-forum-ms:
       image : mongo:latest
       container_name : mongodb-forum-ms
       restart : always 
       volumes :
        - dbdata:/data/db
       ports:
        - "27019:27017"
       networks:
       - medest-network 
       
networks:
    medest-network:
       external: true
       driver : bridge
volumes:
     dbdata :
        driver : local   
       
         