version: '3.7'

services:
  complaint-ms :
      build : 
         context : .
         dockerfile : Dockerfile
      image : node:lastest
      container_name: complaint-ms
      restart : always 
      stdin_open: true 
      tty : true
      command : /usr/src/app/node_modules/.bin/nodemon server.js
      volumes :
        - ./:/usr/src/app
        - /usr/src/app/node_modules
      ports :
       - "5010:5000"
      depends_on:
       - complaint-ms-db
      env_file : ./config/.env
      networks:
       - medest-network

  complaint-ms-db:
       image : mongo:latest
       container_name : complaint-ms-db
       restart : always 
       volumes :
        - dbdata:/data/db
       ports:
        - "27023:27017"
       networks:
       - medest-network
       
networks:
    medest-network:
       external: true
       driver : bridge
volumes:
     dbdata :
        driver : local   
       
         